name: nTags
version: '${project.version}'
main: n2k_.ntags.nTags
api-version: 1.17
load: POSTWORLD
authors: [ neros2k ]
website: github.com/neros2k
commands:
  tag:
    description: The main command.
    aliases: [ntags, nt]
permissions:
  ntags.admin:
    default: op
  ntags.command.*:
    children:
      ntags.command.reload: true
      ntags.command.hide: true
      ntags.command.show: true
softdepend:
  - PlaceholderAPI
depend:
  - JSONConfigAPI